/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClickPointText: typeof import('./../components/ClickPointText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shop: typeof import('./../components/Shop.vue')['default']
    ShopItem: typeof import('./../components/Shop/Item.vue')['default']
    UIButton: typeof import('./../components/UI/Button.vue')['default']
    UIIcon: typeof import('./../components/UI/Icon.vue')['default']
  }
}
